server:
  port: 9002


spring:
  application:
    name: monitor_service
  # 连接redis
  redis:
    host: localhost
    port: 6379

# 配置dubbo服务提供者
#dubbo:
#  registry:
#    address: zookeeper://127.0.0.1:2181
#  application:
#    name: provider-server
#  scan:
#    base-packages: com.engineering.service


